"""empty message

Revision ID: 79371cc40af3
Revises: 
Create Date: 2018-07-23 03:06:47.744422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79371cc40af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osuid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_osuid'), 'users', ['osuid'], unique=True)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourn_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=True),
    sa.ForeignKeyConstraint(['tourn_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcomes',
    sa.Column('team1', sa.Integer(), nullable=False),
    sa.Column('team2', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('mplink', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['team1'], ['tournament_teams.id'], ),
    sa.ForeignKeyConstraint(['team2'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('team1', 'team2')
    )
    op.create_table('players',
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player'], ['users.osuid'], ),
    sa.ForeignKeyConstraint(['team'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('team', 'player')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('outcomes')
    op.drop_table('tournament_teams')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_users_osuid'), table_name='users')
    op.drop_table('users')
    op.drop_table('matches')
    # ### end Alembic commands ###
